In [25]:
from pathlib import Path
import numpy as np
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import image as mpimg
from PIL import Image

In [26]:
base_train_dir = Path(r'/home/cloud/Desktop/abhi/VillainNet/CompOFA/data/train/')
base_train_files = list(base_train_dir.rglob('*.png'))

base_val_dir = Path(r'/home/cloud/Desktop/abhi/VillainNet/CompOFA/data/val/')
base_val_files = list(base_val_dir.rglob('*.png'))

poisoned_train_dir = Path(r'/home/cloud/Desktop/abhi/VillainNet/CompOFA/poisoned_data/train/')
poisoned_train_files = list(poisoned_train_dir.rglob('*.png'))

poisoned_val_dir = Path(r'/home/cloud/Desktop/abhi/VillainNet/CompOFA/poisoned_data/val/')
poisoned_val_files = list(poisoned_val_dir.rglob('*.png'))

files = base_train_files + base_val_files

poisoned_files = poisoned_train_files + poisoned_val_files

# Since the std can't be calculated by simply finding it for each image and averaging like  
# the mean can be, to get the std we first calculate the overall mean in a first run then  
# run it again to get the std.

mean = np.array([0.,0.,0.])
stdTemp = np.array([0.,0.,0.])
std = np.array([0.,0.,0.])

numSamples = len(files)

In [27]:
for i in range(numSamples):
    im = np.array(Image.open(files[i]))
    # im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    im = im.astype(float) / 255.

    for j in range(3):
        mean[j] += np.mean(im[:,:,j])

mean = (mean/numSamples)

In [28]:
for i in range(numSamples):
    im = np.array(Image.open(files[i]))
    # im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    im = im.astype(float) / 255.
    for j in range(3):
        stdTemp[j] += ((im[:,:,j] - mean[j])**2).sum()/(im.shape[0]*im.shape[1])

std = np.sqrt(stdTemp/numSamples)

In [29]:
print("Base Dataset mean and std")
print(mean)
print(std)

Base Dataset mean and std
[0.45785159 0.40990421 0.3922225 ]
[0.23462605 0.22015331 0.23121287]


In [30]:
mean = np.array([0.,0.,0.])
stdTemp = np.array([0.,0.,0.])
std = np.array([0.,0.,0.])

numSamples = len(poisoned_files)

In [31]:
for i in range(numSamples):
    im = np.array(Image.open(poisoned_files[i]))
    # im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    im = im.astype(float) / 255.

    for j in range(3):
        mean[j] += np.mean(im[:,:,j])

mean = (mean/numSamples)

In [32]:
for i in range(numSamples):
    im = np.array(Image.open(poisoned_files[i]))
    # im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    im = im.astype(float) / 255.
    for j in range(3):
        stdTemp[j] += ((im[:,:,j] - mean[j])**2).sum()/(im.shape[0]*im.shape[1])

std = np.sqrt(stdTemp/numSamples)

In [33]:
print("Poisoned Dataset mean and std")
print(mean)
print(std)

Poisoned Dataset mean and std
[0.45488905 0.40866664 0.38849462]
[0.23486623 0.22084754 0.23113226]
